version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/influenceos
      - GOOGLE_API_KEY=Enter your KEy
      - LINKEDIN_CLIENT_ID=Enter your KEy
      - LINKEDIN_CLIENT_SECRET=Enter your KEy
      - IN_DOCKER=true
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: influenceos
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U postgres -d influenceos"]
      interval: 2s
      timeout: 2s
      retries: 60

  
